### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by kitsunenosaraT** [kitsunenosaraT/Mozilla-Italia-l10n-guide#14]

**Comment by kitsunenosaraT** [comment]
Thanks  to @eliogi for formatting and enhancing the [README](README.md) file 😀

**Comment by EugenioPetulla** [comment]
I propose to edit the readme file in order to integrate footnotes instead of using the ^ char that is not so clear: https://github.com/kitsunenosaraT/Mozilla-Italia-l10n-guide/blame/master/README.md#L55

PoC of what I suggest:

This is a text with a note <sup>[[1]](#footnote1)</sup>

<a name="footnote1">[1]</a>: This is the associated footnote

Adding a footnote is easy, you can do it and reference the link with some HTML

`This is a text with a note <sup>[[1]](#footnote1)</sup>

<a name="footnote1">[1]</a>: This is the associated footnote`

If you want I can directly do a pull request. :)
